#!/usr/bin/env just --justfile

@_default:
	just --list

# Prints relevant info for flatpak pypi dependencies
print:
	@python flatpak-pypi-checker.py \
		--dependency PySide6-Essentials==6.7.2::manylinux:x86_64 \
		--dependency shiboken6::manylinux:x86_64 \
		  | jq
